<<<<<<< HEAD
# Generated by Django 2.1 on 2019-08-21 13:03
=======
# Generated by Django 2.2.2 on 2019-08-20 13:39
>>>>>>> 00486efd62bd717f2eaff3e6c9f80a737c54bef9

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('Organizer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Organizer', '0002_auto_20190812_1858'),
>>>>>>> 00486efd62bd717f2eaff3e6c9f80a737c54bef9
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipateEvent',
            fields=[
                ('Event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Organizer.OrganiseEvent')),
                ('us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
