# Generated by Django 2.2.2 on 2019-08-30 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Organizer', '0003_auto_20190830_1821'),
        ('Participant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFeeback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('feedback', models.CharField(max_length=500)),
                ('pubDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('Event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organizer.OrganiseEvent')),
                ('us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
