# Generated by Django 2.1 on 2019-09-22 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sponsor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsortransaction',
            name='org_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Organizer.OrganiseEvent'),
        ),
        migrations.AlterField(
            model_name='sponsortransaction',
            name='us',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
