# Generated by Django 2.1 on 2019-05-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='userType',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
