# Generated by Django 2.2.2 on 2019-08-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190727_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(default=1, upload_to='images/profile/'),
            preserve_default=False,
        ),
    ]
