# Generated by Django 2.1 on 2019-08-21 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile'),
        ('accounts', '0003_userprofile_profile_img'),
    ]

    operations = [
    ]
