# Generated by Django 2.1 on 2019-05-11 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
