# Generated by Django 2.1 on 2019-05-12 19:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Blog', '0002_delete_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('pubDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('imageSecond', models.ImageField(upload_to='images/blogsImages')),
                ('imageFirst', models.ImageField(upload_to='images/blogsImages')),
                ('UserType', models.CharField(max_length=30)),
                ('authorName', models.CharField(max_length=30)),
                ('blogCategory', models.CharField(max_length=30)),
                ('refrenceLinks', models.CharField(max_length=30)),
            ],
        ),
    ]
