# Generated by Django 2.1 on 2019-05-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_blogsinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsinfo',
            name='description',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
