# Generated by Django 2.1 on 2019-06-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_blogsinfo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsinfo',
            name='imageFirst',
            field=models.ImageField(upload_to='images/blogsImages/'),
        ),
        migrations.AlterField(
            model_name='blogsinfo',
            name='imageSecond',
            field=models.ImageField(upload_to='images/blogsImages/'),
        ),
    ]
