# Generated by Django 2.1 on 2019-07-13 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0005_auto_20190628_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsinfo',
            name='us',
            field=models.ForeignKey(default=131, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
