# Generated by Django 2.1 on 2019-08-14 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_blogsinfo_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsinfo',
            name='imageFirst',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='blogsinfo',
            name='imageSecond',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
