# Generated by Django 2.1 on 2019-08-21 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_auto_20190814_1011'),
        ('Blog', '0002_auto_20190727_1159'),
    ]

    operations = [
    ]
