# Generated by Django 2.1 on 2019-05-20 17:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganiseEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=200)),
                ('event_category', models.CharField(max_length=200)),
                ('org_name', models.CharField(max_length=200)),
                ('org_email', models.EmailField(max_length=100)),
                ('org_mobile', models.BigIntegerField()),
                ('org_contact_person', models.CharField(max_length=100)),
                ('event_poster', models.ImageField(upload_to='images/event_poster')),
                ('event_startdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_enddate', models.DateTimeField()),
            ],
        ),
    ]
