# Generated by Django 2.2.3 on 2019-08-24 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organizer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SponsorShipDetails',
        ),
    ]
