# Generated by Django 2.1 on 2019-08-21 13:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Organizer', '0002_auto_20190821_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organiseevent',
            name='event_category',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='organiseevent',
            name='event_description',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='organiseevent',
            name='event_enddate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='organiseevent',
            name='event_poster',
            field=models.ImageField(blank=True, upload_to='images/event_poster/'),
        ),
        migrations.AlterField(
            model_name='organiseevent',
            name='event_startdate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='organiseevent',
            name='org_contact_person',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='organiseevent',
            name='org_email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='organiseevent',
            name='org_mobile',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='organiseevent',
            name='org_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
