# Generated by Django 2.1 on 2019-05-26 13:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Organizer', '0002_eventdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1500)),
                ('publishedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('resourceLink', models.CharField(max_length=100)),
                ('documentFile', models.FileField(upload_to='shared_resources_docs')),
                ('publisedBy', models.CharField(max_length=100)),
                ('resourceImage', models.ImageField(upload_to='shared_resources')),
            ],
        ),
    ]
