# Generated by Django 2.2.3 on 2019-07-30 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organizer', '0002_auto_20190727_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLocation',
            fields=[
                ('event_venue_name', models.CharField(max_length=200)),
                ('event_venue_addr', models.CharField(max_length=300)),
                ('event_latitude', models.CharField(max_length=100)),
                ('event_longitude', models.CharField(max_length=100)),
                ('event_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Organizer.EventDetails')),
            ],
        ),
    ]
