# Generated by Django 2.2.3 on 2019-08-12 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organizer', '0002_auto_20190812_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organiseevent',
            name='event_description',
        ),
    ]
