# Generated by Django 2.2.3 on 2019-08-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizer', '0003_remove_organiseevent_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='organiseevent',
            name='event_description',
            field=models.CharField(default=1, max_length=800),
            preserve_default=False,
        ),
    ]
