# Generated by Django 2.1 on 2019-08-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizer', '0003_auto_20190821_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organiseevent',
            name='event_poster',
            field=models.ImageField(upload_to='images/event_poster/'),
        ),
    ]
