# Generated by Django 2.1 on 2019-05-27 21:37

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Organizer', '0003_shareresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platinum_sponsor', models.CharField(max_length=100)),
                ('f_platinum', models.IntegerField()),
                ('ex_platinum', models.CharField(max_length=100)),
                ('gold_sponsor', models.CharField(max_length=100)),
                ('f_gold', models.TextField(max_length=1500)),
                ('ex_gold', models.TextField(max_length=1500)),
                ('silver_sponsor', models.CharField(max_length=100)),
                ('f_silver', models.TextField(max_length=1500)),
                ('ex_silver', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='shareresource',
            name='publisedBy',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
