# Generated by Django 2.2.3 on 2019-08-12 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organizer', '0003_eventlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlocation',
            name='event_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventlocation',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organizer.OrganiseEvent'),
        ),
        migrations.AlterField(
            model_name='organiseevent',
            name='event_description',
            field=models.CharField(max_length=800),
        ),
    ]
