# Generated by Django 2.2.3 on 2019-08-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizer', '0004_organiseevent_event_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_location',
            name='eventid',
        ),
        migrations.AddField(
            model_name='event_location',
            name='eventid',
            field=models.ManyToManyField(to='Organizer.OrganiseEvent'),
        ),
    ]
