# Generated by Django 2.1 on 2019-08-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizer', '0004_auto_20190814_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organiseevent',
            name='event_poster',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
