# Generated by Django 2.1 on 2019-05-28 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizer', '0004_auto_20190528_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorship',
            name='ex_gold',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='ex_platinum',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='f_platinum',
            field=models.TextField(max_length=1500),
        ),
    ]
