# Generated by Django 2.2.3 on 2019-08-12 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organizer', '0004_auto_20190812_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventlocation',
            old_name='event_id',
            new_name='eventid',
        ),
    ]
