# Generated by Django 2.1 on 2019-08-21 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organizer', '0005_auto_20190819_1518'),
        ('Organizer', '0002_auto_20190812_1858'),
    ]

    operations = [
    ]
