# Generated by Django 2.2.3 on 2019-08-12 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organizer', '0005_auto_20190812_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_location',
            name='eventid',
        ),
        migrations.AddField(
            model_name='event_location',
            name='eventid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Organizer.OrganiseEvent'),
            preserve_default=False,
        ),
    ]
