# Generated by Django 2.1 on 2019-05-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizer', '0005_auto_20190528_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorship',
            name='event_title',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
