# Generated by Django 2.1 on 2019-06-01 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organizer', '0006_sponsorship_event_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorShipDetails',
            fields=[
                ('event_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Organizer.EventDetails')),
                ('event_title', models.CharField(default=True, max_length=100)),
                ('platinum_sponsor', models.CharField(max_length=100)),
                ('f_platinum', models.TextField(max_length=1500)),
                ('ex_platinum', models.IntegerField()),
                ('gold_sponsor', models.CharField(max_length=100)),
                ('f_gold', models.TextField(max_length=1500)),
                ('ex_gold', models.IntegerField()),
                ('silver_sponsor', models.CharField(max_length=100)),
                ('f_silver', models.TextField(max_length=1500)),
                ('ex_silver', models.IntegerField()),
            ],
        ),
    ]
