# Generated by Django 2.1 on 2019-06-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizer', '0007_sponsorshipdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='event_detail_docs',
            field=models.FileField(upload_to='images/event_details_docs'),
        ),
    ]
