# Generated by Django 2.1 on 2019-06-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizer', '0008_auto_20190614_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='eligibility',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='event',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='event_level',
            field=models.CharField(max_length=200),
        ),
    ]
