# Generated by Django 2.1 on 2019-06-21 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizer', '0010_eventdetails_expected_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareresource',
            name='documentFile',
            field=models.FileField(upload_to='Images/shared_resources_docs'),
        ),
        migrations.AlterField(
            model_name='shareresource',
            name='publisedBy',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shareresource',
            name='resourceImage',
            field=models.ImageField(upload_to='Images/shared_resources'),
        ),
    ]
