# Generated by Django 2.1 on 2019-06-21 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizer', '0011_auto_20190621_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareresource',
            name='documentFile',
            field=models.FileField(upload_to='images/shared_resources_docs'),
        ),
        migrations.AlterField(
            model_name='shareresource',
            name='resourceImage',
            field=models.ImageField(upload_to='images/shared_resources'),
        ),
    ]
