# Generated by Django 2.1 on 2019-06-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizer', '0013_auto_20190622_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organiseevent',
            name='event_poster',
            field=models.ImageField(upload_to='images'),
        ),
    ]
