# Generated by Django 2.1 on 2019-06-23 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizer', '0017_auto_20190622_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='organiseevent',
            name='event_description',
            field=models.CharField(default=True, max_length=800),
        ),
    ]
