# Generated by Django 2.1 on 2019-06-23 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizer', '0018_organiseevent_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organiseevent',
            name='event_description',
            field=models.CharField(max_length=800),
        ),
    ]
