# Generated by Django 2.1 on 2019-07-05 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Organizer', '0021_auto_20190705_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organiseevent',
            name='us_id',
        ),
        migrations.AddField(
            model_name='organiseevent',
            name='us',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
            preserve_default=False,
        ),
    ]
