# Generated by Django 2.1 on 2019-07-06 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organizer', '0023_auto_20190706_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareresource',
            name='orgId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organizer.OrganiseEvent'),
        ),
    ]
