# Generated by Django 2.1 on 2019-07-06 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organizer', '0024_auto_20190706_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareresource',
            name='orgId',
            field=models.ForeignKey(default=50, on_delete=django.db.models.deletion.CASCADE, to='Organizer.OrganiseEvent'),
        ),
    ]
