# Generated by Django 2.1 on 2019-07-13 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Organizer', '0025_auto_20190706_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='us',
            field=models.ForeignKey(default=131, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shareresource',
            name='us',
            field=models.ForeignKey(default=131, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='us',
            field=models.ForeignKey(default=131, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sponsorshipdetails',
            name='us',
            field=models.ForeignKey(default=131, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
