# Generated by Django 2.1 on 2019-07-13 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organizer', '0027_auto_20190713_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareresource',
            name='orgId',
        ),
    ]
