# Generated by Django 2.1 on 2019-07-13 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organizer', '0028_remove_shareresource_orgid'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='org_id',
            field=models.ForeignKey(default=50, on_delete=django.db.models.deletion.CASCADE, to='Organizer.OrganiseEvent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shareresource',
            name='org_id',
            field=models.ForeignKey(default=50, on_delete=django.db.models.deletion.CASCADE, to='Organizer.OrganiseEvent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='org_id',
            field=models.ForeignKey(default=50, on_delete=django.db.models.deletion.CASCADE, to='Organizer.OrganiseEvent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsorshipdetails',
            name='org_id',
            field=models.ForeignKey(default=50, on_delete=django.db.models.deletion.CASCADE, to='Organizer.OrganiseEvent'),
            preserve_default=False,
        ),
    ]
