# Generated by Django 2.1 on 2019-05-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0004_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_date',
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default=678687, max_length=100),
            preserve_default=False,
        ),
    ]
