# Generated by Django 2.1 on 2019-05-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide1', models.ImageField(upload_to='images/')),
                ('slide2', models.ImageField(upload_to='images/')),
                ('slide3', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
