# Generated by Django 2.1 on 2019-06-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisationName', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('maplocation', models.CharField(max_length=600)),
            ],
        ),
        migrations.AlterField(
            model_name='slider',
            name='slide1',
            field=models.ImageField(upload_to='images/slider/'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slide2',
            field=models.ImageField(upload_to='images/slider/'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slide3',
            field=models.ImageField(upload_to='images/slider/'),
        ),
    ]
