# Generated by Django 2.1 on 2019-06-26 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190627_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourpartner',
            name='orgLogo',
            field=models.ImageField(default=True, upload_to='images/OurPartner/'),
        ),
    ]
